<?php
$cfg = array(
'shopnm' => 'ZORDER', 
'shopurl' => 'http://zorder.wooriyo.com/', 
'shopem' => 'intl@zorder.com', 
'shopadm' => 'ZORDER', 
'comnm' => 'ZORDER', 
'comceo' => 'ZORDER', 
'comserial' => '123-45-5678', 
'comsaleno' => '제11-12345호', 
'comtel' => '+82 63 734 4433', 
'comfax' => '+82 63 734 4433', 
'comzip' => '', 
'comadr' => '262, Gonghang-ro, Gunsan-si, Jeollabuk-do, Republic of Korea', 
'df_dyamt' => '2500', 
'non_dyamt' => '50000', 
'cartDay' => '7', 
'mouseEvent' => 'N', 
'shoptit' => 'ZORDER', 
'shopkeyword' => '', 
'shopinfo' => '', 
'naver_key' => '', 
'unid' => 'admin,sadm,zorder,shop,mall', 
'pg' => 'kcp', 
'site_cd' => 'T0007', 
'site_key' => '4Ho4YsuOZlLXUZUdOxM1Q7X__', 
'site_path' => '/home/zorder/_sys/_kcp', 
'site_name' => 'Zorder', 
'quotaopt' => '0', 
'card' => 'Y', 
'bank' => 'Y', 
'esbank' => 'N', 
'vcnt' => 'Y', 
'esvcnt' => 'N', 
'mobx' => 'Y', 
'sbank' => 'Y', 
'bsms' => 'N', 
'sms' => 'aligo', 
'sms_id' => '', 
'sms_key' => '', 
'sender' => '', 
'receive' => '', 
'adm_ipaccess' => 'N', 
'kakao' => 'https://accounts.kakao.com/login/kakaostory', 
'facebook' => 'https://www.facebook.com/', 
'instagram' => 'http://www.instagram.com', 
'blog' => 'https://section.blog.naver.com', 
'fcustomer' => '10:00am ~ 17:00pm
(Lunch 12:20pm - 13:00pm)
Sat, Sun, Holiday OFF', 
'freturn' => '262, Gonghang-ro, Gunsan-si, Jeollabuk-do, Republic of Korea
(자세한 교환·반품절차 안내는
공지사항을 참고해주세요)', 
'naverpay' => 'N', 
'point' => ''
);
?>